# 系统模块数据库
spring: 
 datasource: 
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@192.168.55.226:1521:tms5db
  username: tms_sys
  password: hwsoft
  initialSize: 5
  minIdle: 5
  maxActive: 50
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true 
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 50
  # filters: stat
  connectionProperties: druid.stat.slowSqlMillis=5000;druid.stat.mergeSql=true
  useGlobalDataSourceStat: true
 http: 
  multipart: 
   maxFileSize: 1000MB
   max-file-size: 2000MB
   max-request-size: 2000MB

fw: 
 elasticsearch:
  log:
   clusterName: es-application
   clusterNodes: 192.168.55.226:9300

  eslog: 
    calllog: 
      indexPrefix: fw_log_call_dev
      maxSearchDay: 15
      
